//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretAgency.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecretAgency.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resources at your disposal..
        /// </summary>
        internal static string Assets_Label_Tooltip {
            get {
                return ResourceManager.GetString("Assets_Label_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date.
        /// </summary>
        internal static string Date_Label_Tooltip {
            get {
                return ResourceManager.GetString("Date_Label_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days until the next Review is scheduled. Make sure your polls rating is high and heat level is low..
        /// </summary>
        internal static string DaysTillReview_Label_Tooltip {
            get {
                return ResourceManager.GetString("DaysTillReview_Label_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your budget for spreading false or otherwise information about an individual or a group..
        /// </summary>
        internal static string Disinformation_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("Disinformation_ListItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your overall level of indiscretion. Try to keep it as low as possible or you might find yourself replaced..
        /// </summary>
        internal static string Heat_Label_Tooltip {
            get {
                return ResourceManager.GetString("Heat_Label_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-army unit with enough munitions to destroy any civilian or paramilitary group.
        /// </summary>
        internal static string HeavyAssault_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("HeavyAssault_ListItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of agents ready to infiltrate a group.
        /// </summary>
        internal static string Infiltration_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("Infiltration_ListItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capable of abducting a person for interrogation..
        /// </summary>
        internal static string Interrogation_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("Interrogation_ListItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Director-General.
        /// </summary>
        internal static string PlayerName_Textbox_Tooltip {
            get {
                return ResourceManager.GetString("PlayerName_Textbox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The popular opinion of the Party you are representing. Keep it at or above 50%, especially during a Review..
        /// </summary>
        internal static string Polls_Label_Tooltip {
            get {
                return ResourceManager.GetString("Polls_Label_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specialized team capable of tracking and reporting the movement of an individual.
        /// </summary>
        internal static string Pursuit_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("Pursuit_ListItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialist tasked with permanent physical removal of individuals.
        /// </summary>
        internal static string Removal_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("Removal_ListItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be ordered to either search or raid a location for any items..
        /// </summary>
        internal static string Search_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("Search_ListItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specialized team capable of spying on any individual&apos; or group&apos;s location..
        /// </summary>
        internal static string Surveillance_ListItem_Tooltip {
            get {
                return ResourceManager.GetString("Surveillance_ListItem_Tooltip", resourceCulture);
            }
        }
    }
}
